### ISSUE TITLE
Can't regex process <hX> when X is an integer

### ISSUE THREAD

**Issue by bloo** [thlorenz/doctoc#36]
It works for any other letter besides "h", but breaks when in angle brackets, pared with an integer - whether the brackets are escaped or not.

good:
```
a1
<a1>
\<a1\>
h1
<9h>
```

bad:
```
<h2>
\<h2\>
\<hh2\>
\<h2h\>
```
Here's the stack:
```
/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:11
      if (new RegExp(x.text[0]).test(line)) {
          ^
SyntaxError: Invalid regular expression: /

* HTML5 container semantics
  * proper use of [**\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at /usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:11:11
    at Array.map (native)
    at addLinenos (/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:8:18)
    at module.exports (/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:66:13)
    at transform (/usr/local/lib/node_modules/doctoc/lib/transform.js:127:13)
    at /usr/local/lib/node_modules/doctoc/doctoc.js:26:20
    at Array.map (native)
    at transformAndSave (/usr/local/lib/node_modules/doctoc/doctoc.js:24:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/doctoc/doctoc.js:66:1)
```

**Comment by RyanZim** [comment]
Is this fixed by https://github.com/thlorenz/doctoc/pull/107?

**Comment by thlorenz** [comment]
Should be, closing since no action for over a year.

**Comment by mkfreeman** [comment]
Hi, 

I'm having the same issue while writing README documents that describe HMTL elements (namely headers):

```
DocToccing single file "README.md" for github.com.

==================

/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:11
      if (new RegExp(x.text[0]).test(line)) {
          ^

SyntaxError: Invalid regular expression: /` element tells the reader that the content inside is a top-level heading.

The end tag is just like the start tag except that it has a forward slash added just after the less-than sign (`/: Unterminated group
    at new RegExp (native)
    at /usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:11:11
    at Array.map (native)
    at addLinenos (/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:8:18)
    at module.exports (/usr/local/lib/node_modules/doctoc/lib/get-html-headers.js:66:13)
    at transform (/usr/local/lib/node_modules/doctoc/lib/transform.js:123:13)
    at /usr/local/lib/node_modules/doctoc/doctoc.js:25:20
    at Array.map (native)
    at transformAndSave (/usr/local/lib/node_modules/doctoc/doctoc.js:23:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/doctoc/doctoc.js:100:3)

```

When I use any other tag (besides `<h1>`) I'm fine. Any thoughts/progress on this?

**Comment by RyanZim** [comment]
@mkfreeman Please open a new issue for this and provide a snippet of the markdown that causes this error.

**Comment by mkfreeman** [comment]
@RyanZim done, thanks: #120
